import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import React from 'react';

export default function AdminDashboard() {
  const router = useRouter();
  const [currentUser, setCurrentUser] = useState(null);
  const [activeTab, setActiveTab] = useState('inventory');
  const [products, setProducts] = useState(() => { if (typeof window !== 'undefined') { const saved=localStorage.getItem('admin_products'); return saved?JSON.parse(saved):[]; } return []; });
  const [loading, setLoading] = useState(false);
  const formatAttributes = a => !Array.isArray(a)||!a.length?'':a.map(x=>`${x.name||x.slug||'Optie'}: ${x.option||'Standaard'}`).join(' | ');
  useEffect(()=>{const u=localStorage.getItem('pos_user');if(!u){router.replace('/login');return;}try{const p=JSON.parse(u);if(p.role!=='admin'&&p.role!=='super_admin'){router.replace('/');return;}setCurrentUser(p);fetchProducts();}catch(_){router.replace('/login');}},[router]);
  const fetchProducts=async()=>{try{const r=await fetch('/api/woocommerce/products?refresh=1',{cache:'no-store',headers:{'Cache-Control':'no-cache, no-store, must-revalidate','Pragma':'no-cache'}});const d=await r.json();if(d.success&&Array.isArray(d.products)){setProducts(d.products);localStorage.setItem('admin_products',JSON.stringify(d.products));return d.products;}throw new Error(d.error||`HTTP ${r.status}`);}catch(e){console.error('[ADMIN PRODUCTS]',e);return[];}};
  const sync=async()=>{setLoading(true);const list=await fetchProducts();setLoading(false);if(list.length)alert(`${list.length} producten succesvol gesynchroniseerd!`);else alert('Product sync mislukt: geen producten ontvangen.');};
  return <div className="min-h-screen bg-gray-100"><header className="bg-black text-white p-4"><div className="flex justify-between"><h1 className="text-xl font-black">BDM POS // Admin Dashboard</h1><Link href="/" className="bg-gray-800 px-4 py-2 rounded font-bold">🛒 Terug naar Kassa</Link></div></header><div className="bg-white border-b p-2 flex gap-2"><button className="bg-red-600 text-white px-4 py-2 rounded text-xs font-bold">📦 Voorraad & Variaties</button></div><main className="p-6 max-w-7xl mx-auto"><section className="bg-white rounded-lg shadow p-6"><div className="flex justify-between items-center border-b pb-3 mb-4"><h3 className="font-bold">📦 Producten & Variaties Voorraad ({products.length})</h3><button onClick={sync} disabled={loading} className="bg-black text-white px-3 py-2 rounded text-xs font-bold">{loading?'⏳ Laden...':'🔄 Sync'}</button></div><table className="w-full text-left text-xs"><thead><tr className="bg-gray-50"><th className="p-3">ID</th><th className="p-3">Naam</th><th className="p-3">Prijs</th><th className="p-3">Voorraad</th></tr></thead><tbody>{products.map(p=><React.Fragment key={p.id}><tr className="border-b"><td className="p-3">#{p.id}</td><td className="p-3 font-semibold">{p.name}</td><td className="p-3">{p.price?`€${parseFloat(p.price).toFixed(2)}`:'Vanaf prijs'}</td><td className="p-3">{p.stock_quantity??'N.v.t.'}</td></tr>{p.type==='variable'&&(p.variations_data||[]).map(v=><tr key={`v_${v.id}`} className="bg-gray-50"><td className="p-3">↳ #{v.id}</td><td className="p-3">{formatAttributes(v.attributes)||`Variatie #${v.id}`}</td><td className="p-3">€{parseFloat(v.price||p.price||0).toFixed(2)}</td><td className="p-3">{v.stock_quantity??'N.v.t.'}</td></tr>)}</React.Fragment>)}</tbody></table></section></main></div>;
}